# Generated by Django 4.2.3 on 2023-10-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slot_post", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
