version : "3.8"
services:
    app:
      build: .
      volumes:
        - .:/user
      ports:
        - 8001:8001
      image : app:user
      container_name: user_container
      command : python manage.py runserver 0.0.0.0:8001
