# Generated by Django 4.2.5 on 2023-10-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LikedPosts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("PostId", models.IntegerField(unique=True)),
                ("PostTitle", models.CharField(max_length=1500)),
            ],
        ),
    ]
