version : "3.8"
services:
    app:
      build: .
      volumes:
        - .:/doctor
      ports:
        - 8000:8000
      image : app:doctor
      container_name: doctor_container
      command : python manage.py runserver 0.0.0.0:8000
